language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-widget' ]; then cd .. && eval "mv $currentfolder generator-widget" && cd generator-widget; fi

